$pdf_mode = 5; # -xelatex

$pdf_previewer = 'okular --unique';
$xelatex = 'xelatex -file-line-error -halt-on-error -shell-escape -synctex=1 -interaction=batchmode %O %S';

@generated_exts = (@generated_exts, 'synctex.gz');
@default_files = ('main.tex');

# .latexmkrc ends
